In [1]:
import numpy as np #numpy의 별칭 np 
print(np.__version__)

2.4.2


- 데이터 분석 : 수치형 변수의 요약, 통계, 시각화
- 이미지처리: 이미지데이터
- 게임/시뮬레이션: 시뮬레이션 구현
- 머신러닝/딥러닝: 금융,의료,실험,센서 데이터

In [4]:
arr = np.array([1,2,3,4,5])
print(arr,type(arr)) # [1 2 3 4 5]

[1 2 3 4 5] <class 'numpy.ndarray'>


# 넘파이 배열의 속성 ndarray

In [7]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print("합계:", arr.sum())          # 21
print("평균:", arr.mean())         # 3.5
print("표준편차:", arr.std())      # 1.707825127659933
print("행 방향 합계:", arr.sum(axis=1))  # [6 15]
print("열 방향 평균:", arr.mean(axis=0))  # [2.5 3.5 4.5]
arr.shape

합계: 21
평균: 3.5
표준편차: 1.707825127659933
행 방향 합계: [ 6 15]
열 방향 평균: [2.5 3.5 4.5]


(2, 3)

In [15]:
np.array(7).shape, np.array(7).ndim #0차원

((), 0)

In [12]:
np.array([7]).shape , np.array([7]).ndim #1차원,열1개

((1,), 1)

In [13]:
np.array([7,2]).shape , np.array([7,2]).ndim #1차원,열2개

((2,), 1)

In [16]:
arr1 = np.array([1, 2, 3, 4, 5]) #arr1.shape : (5,0)
arr12 = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10]
]) #arr12.shape : (2,5)

arr1.shape, arr12.shape

((5,), (2, 5))

In [17]:
# (3,5) 행렬 arr13 만들기
arr13 = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11,12,13,14,15]])

arr13.shape

(3, 5)

In [20]:
arr13 = np.arange(1,16).reshape(3,5)
arr13.shape

(3, 5)

In [56]:
arr13.dtype

dtype('int64')

# array 의 생성법

In [22]:
# 0으로 채워진 배열 생성
arr2 = np.zeros(5)

In [21]:
# 1로 채워진 배열 생성
arr3 = np.ones((3, 3))

In [25]:
# 1부터 10까지 2씩 증가하는 배열
range_arr = np.arange(1, 10, 2)  
print(range_arr)

[1 3 5 7 9]


In [23]:
 # 0부터 100까지 5개의 숫자를 균등 간격으로 생성
linspace_arr = np.linspace(0, 100, 5) 
print(linspace_arr)

[  0.  25.  50.  75. 100.]


In [26]:
# 2행 3열의 랜덤 값 배열 (0~1 사이)
random_arr = np.random.rand(2, 3) 
print(random_arr)

[[0.93317284 0.83855906 0.66563494]
 [0.79414416 0.98662456 0.46484847]]


# #넘파이의 데이터타입

In [29]:
# 다양한 데이터 타입의 배열 생성
#dtype 속성; np.int32 상수, ‘int32’ 문자열 형식으로 지정
int_array = np.array([1, 2, 3], dtype=np.int32)
float_array = np.array([1.0, 2.0, 3.0], dtype=np.float64)
bool_array = np.array([True, False, True], dtype=np.bool_)

print("정수 배열의 dtype:", int_array.dtype)
print("실수 배열의 dtype:", float_array.dtype)
print("불리언 배열의 dtype:", bool_array.dtype)

정수 배열의 dtype: int32
실수 배열의 dtype: float64
불리언 배열의 dtype: bool


# array 의 데이터 타입 변환

In [30]:
# 데이터 타입 변환 예제
float_arr = np.array([1.1, 2.2, 3.3])
int_arr = float_arr.astype(np.int32)  # 실수를 정수로 변환
print("변환 전:", float_arr, float_arr.dtype)
print("변환 후:", int_arr, int_arr.dtype)

변환 전: [1.1 2.2 3.3] float64
변환 후: [1 2 3] int32


In [32]:
# 1차원 배열 생성
a = np.arange(12)
print(a)  # [ 0  1  2  3  4  5  6  7  8  9 10 11]

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [33]:
# 2차원 배열로 변환 (3x4)
b = a.reshape(3, 4)
print(b)
# [[ 0  1  2  3]
#  [ 4  5  6  7]
#  [ 8  9 10 11]]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [34]:
# 3차원 배열로 변환 (2x2x3)
c = a.reshape(2, 2, 3)
print(c)
# [[[ 0  1  2]
#   [ 3  4  5]]
#  [[ 6  7  8]
#   [ 9 10 11]]]

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]


In [37]:
data = [
  [120, 135,150,145], #제품 A
  [100, 110, 140, 130], #제품 B
  [90, 100, 95, 105]] #제품 C

type (data)

list

In [38]:
#생산량 합계 확인
total_production = [sum(product) for product in data]
total_production

[550, 480, 390]

In [40]:
prod_data = np.array(data)
prod_data.shape

(3, 4)

In [42]:
np.sum(prod_data, axis=1)

array([550, 480, 390])

In [59]:
prod_data*2

array([[240, 270, 300, 290],
       [200, 220, 280, 260],
       [180, 200, 190, 210]])

In [45]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr + 2)  # [3, 4, 5, 6, 7]
print(arr * 3)  # [3, 6, 9, 12, 15]
print(2 ** arr)  # [2, 4, 8, 16, 32]

[3 4 5 6 7]
[ 3  6  9 12 15]
[ 2  4  8 16 32]


In [ ]:
# 기본 산술 연산 예제 : 요소별 연산 elements wise
arr1 = np.array([1, 2, 3, 4])
arr2 = np.array([5, 6, 7, 8])

# 덧셈
print("덧셈:", arr1 + arr2)  # [6 8 10 12]

# 뺄셈
print("뺄셈:", arr2 - arr1)  # [4 4 4 4]

# 곱셈
print("곱셈:", arr1 * arr2)  # [5 12 21 32]

# 나눗셈
print("나눗셈:", arr2 / arr1)  # [5. 3. 2.33... 2.]

# 제곱
print("제곱:", np.square(arr1))  # [1 4 9 16]

# 제곱근
print("제곱근:", np.sqrt(arr1))  # [1. 1.41421356 1.73205081 2.]

# 지수
print("지수:", np.exp(arr1))  # [2.71828183 7.3890561 20.08553692 54.59815003]

# 로그
print("로그:", np.log(arr1))  # [0. 0.69314718 1.09861229 1.38629436]

덧셈: [ 6  8 10 12]
뺄셈: [4 4 4 4]
곱셈: [ 5 12 21 32]
나눗셈: [5.         3.         2.33333333 2.        ]
제곱: [ 1  4  9 16]
제곱근: [1.         1.41421356 1.73205081 2.        ]
지수: [ 2.71828183  7.3890561  20.08553692 54.59815003]
로그: [0.         0.69314718 1.09861229 1.38629436]


In [49]:
prod_data

array([[120, 135, 150, 145],
       [100, 110, 140, 130],
       [ 90, 100,  95, 105]])

In [50]:
#생산량 * 단가(이익률) = 총매출(총이익)
profit_per_unit = np.array([20,30,25])

In [53]:
# 제품별 총 생산량 
total_produc = prod_data.sum(axis=1)
total_produc

array([550, 480, 390])

In [54]:
# 총생산량 * 단가
total_amt = total_produc * profit_per_unit
total_amt

array([11000, 14400,  9750])

# shape 이 다른 배열간 연산에서 ValueError

In [ ]:
# shape이 같은 배열 간의 연산
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

print("덧셈:\n", a + b)
print("뺄셈:\n", a - b)
print("곱셈:\n", a * b)
print("나눗셈:\n", a / b)

# shape이 다른 경우 오류 발생
c = np.array([[1, 2, 3], [4, 5, 6]])  # shape: (2, 3)
d = np.array([[1, 2], [3, 4]])        # shape: (2, 2)

# 이 연산은 오류를 발생시킴
print(c + d)  # ValueError: operands could not be broadcast together

덧셈:
 [[ 6  8]
 [10 12]]
뺄셈:
 [[-4 -4]
 [-4 -4]]
곱셈:
 [[ 5 12]
 [21 32]]
나눗셈:
 [[0.2        0.33333333]
 [0.42857143 0.5       ]]


ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

# 브로드캐스팅(Broadcasting) 3가지 예제

In [62]:
a = np.arange(3) + 5
a

array([5, 6, 7])

In [ ]:
np.ones((3, 3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [65]:
a = np.arange(3).reshape(3, 1) + np.arange(3)
a

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [66]:
# 2차원 배열 예제
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])

# axis=0 방향 합계 (열 방향 합)
sum_axis0 = np.sum(arr_2d, axis=0)  # [5, 7, 9]

# axis=1 방향 합계 (행 방향 합)
sum_axis1 = np.sum(arr_2d, axis=1)  # [6, 15]

In [67]:
# 1차원 배열 인덱싱
arr = np.array([1, 2, 3, 4, 5])
print(arr[0])    # 첫 번째 요소: 1
print(arr[-1])   # 마지막 요소: 5

# 2차원 배열 인덱싱
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6]])
print(arr_2d[0, 1])    # 첫 번째 행, 두 번째 열: 2
print(arr_2d[1, -1])   # 두 번째 행, 마지막 열: 6

1
5
2
6


In [68]:
# 1차원 배열 슬라이싱
arr = np.array([0, 1, 2, 3, 4, 5])
print(arr[2:5])    # [2 3 4]
print(arr[::2])    # [0 2 4]

# 2차원 배열 슬라이싱
arr_2d = np.array([[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])
print(arr_2d[:2, 1:3])    # 처음 두 행, 두 번째와 세 번째 열
# [[2 3]
#  [6 7]]

[2 3 4]
[0 2 4]
[[2 3]
 [6 7]]


In [87]:
page = np.arange(36).reshape(6, 6)
arr_3d_new = np.array([page]*4)
print(arr_3d_new)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]
  [24 25 26 27 28 29]
  [30 31 32 33 34 35]]]


In [88]:
result = arr_3d_new[0, :3, :3]
print(result)

[[ 0  1  2]
 [ 6  7  8]
 [12 13 14]]


In [89]:
# 불린 인덱싱 예제
arr = np.array([1, 2, 3, 4, 5])
bool_array = np.array([True, False, True, False, True])
print("불린 인덱싱:", arr[bool_array])  # [1 3 5]

불린 인덱싱: [1 3 5]


In [90]:
mask = arr > 3 #조건식으로 마스크 생성
mask

array([False, False, False,  True,  True])

In [91]:
arr[mask]

array([4, 5])

In [92]:
arr

array([1, 2, 3, 4, 5])